services:
  - type: web
    name: safdarali-backend
    runtime: docker
    plan: free
    region: singapore
    autoDeploy: true

    dockerfilePath: ./Dockerfile
    envVars:
      - key: JAVA_VERSION
        value: 17
